name: Deploy to AKS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: "MyCloudDemoGroup"
          cluster-name: "doan-aks-cluster"

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/deployment.yaml --force
          kubectl apply -f k8s/service.yaml
